name: HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: /
